### PR TITLE
Igonchar/tcomp 513

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**What is the current behavior?** (You can also link to an open issue here)

Runtime API classes work with any object

**What is the new behavior?**

Runtime API classes work with IndexedRecord instances

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Related to https://jira.talendforge.org/browse/TCOMP-513

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/767/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/767/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/768/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/768/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/769/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/769/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/773/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/773/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/780/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/780/)

**Comment by gonchar-ivan** [comment]
The work is postponed. I'll create another PR, when it will be ready.

**Pull request closed without merging**
