### PR TITLE
Fix/devops 1517

### PR DESCRIPTION
**Pull request by sbaryakov**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/475/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/475/)

**Comment by sgandon** [comment]
@sbaryakov coud you add more explanation on the PR initial comment to explain what this PR does please ?

**Comment by sbaryakov** [comment]
The purpose of this is to allow the integration test to work on environment where docker is on remote host (DOCKER_HOST). The maven docker plugin does already respect the DOCKER_HOST environment, however due to the design of the plugin it's not possible to pass the DOCKER_HOST to a container. ${docker.host.address} is not available at the time the container is launched so we have to work around this limitation by manually evaluation the environment variable and making it available via the maven helper plugin.

**Comment by sgandon** [comment]
So why only on the kafka module ? this is not the only one using docker for integration tests.
the Module _components-jira_ and _components-splunk_ are also using docker.
and we also use the docker plugin to build a docker image in service _services/components-api-service-rest-all-components/pom.xml_

**Comment by sbaryakov** [comment]
The components-splunk and jira work fine, because they don't have to know(announce) their own location, kafka is a "special" case in this regards.

**Comment by sgandon** [comment]
please merge when ever you need to.

**Comment by sbaryakov** [comment]
chore(DEVOPS-1517): allow integration test in remote docker environment

**Pull request merged**
