### PR TITLE
Mbasiuk/tdi 39687 snowlake row single mode

### PR DESCRIPTION
**Pull request by mbasiuk-talend**
**What is the current behavior?** (You can also link to an open issue here)
Batch mode

**What is the new behavior?**
Single execution mode.

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [x] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1400/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1400/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Ambasiuk%2FTDI-39687_snowlake_row_single_mode)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1404/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1404/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Ambasiuk%2FTDI-39687_snowlake_row_single_mode)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1418/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1418/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Ambasiuk%2FTDI-39687_snowlake_row_single_mode)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1420/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1420/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Ambasiuk%2FTDI-39687_snowlake_row_single_mode)

**Comment by dmytro-sylaiev** [comment]
Please check my comments for 1038 PR (https://github.com/Talend/components/pull/1038)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1427/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1427/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1429/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1429/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Ambasiuk%2FTDI-39687_snowlake_row_single_mode)

**Comment by mbasiuk-talend** [comment]
Wrong development branch pull request. Must be used **mbasiuk/TDI-39295_dev** as main one.

**Pull request closed without merging**
