### PR TITLE
fix(TDI-43011): Migrate component jobs jenkins1 to jenkins2

### PR DESCRIPTION
**Pull request by wwang-talend**

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/597/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/597/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/636/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/636/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/638/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/638/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/766/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/766/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/767/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/767/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/768/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/768/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/769/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/769/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/770/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/770/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/771/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/771/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/772/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/772/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/773/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/773/)

**Review by vyu-talend — APPROVED** [review]

**Review by jzhao-talend — APPROVED** [review]
LGTM

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/774/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/774/)

**Pull request merged**
