### PR TITLE
TDI-43809 - Update Snakeyaml

### PR DESCRIPTION
**Pull request by coheigea**
The 1.26 release of Snakeyaml contains some additional protection against denial of service attacks - we should upgrade.

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/267/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/267/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/490/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/490/)

**Comment by coheigea** [comment]
@mbasiuk-talend  - The same changes had to be made to the master PR, I've updated the PR - please review + test again.

**Review by mbasiuk-talend — APPROVED** [review]
LGTM.

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/495/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/495/)

**Pull request merged**
