### PR TITLE
Bug/6.3/tdi 37655 fix

### PR DESCRIPTION
**Pull request by wwang-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-37655

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by wwang-talend** [comment]
the test fail as some other reason, not caused by the fix.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/291/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/291/)

**Comment by wwang-talend** [comment]
the merge to master test fail as : 
org.talend.components.api.exception.ComponentException: COMPUTE_DEPENDENCIES_FAILED:{path=META-INF/maven/org.talend.components/components-jdbc-runtime/dependencies.txt}
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveLatestVersionRange(AetherBasedResolver.java:844)

It's an known framework issue,  we can make it success like this : 
Step 1 : mvn clean install -skipTest
Step 2 : mvn c lean install

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/294/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/294/)

**Comment by RyanSkraba** [comment]
Hello!  From the attached JIRA, it looks like this has been fixed already?  Is this PR still relevant?

If so, would it be possible to resolve the conflicts with master (with all of the moved files...!)  and I'll take a look!  Thanks!

**Comment by wwang-talend** [comment]
create a new pr : https://github.com/Talend/components/pull/485 instead of this one, so delete this one.

**Pull request closed without merging**
