### PR TITLE
fix(DEVOPS-3524): align simple rest docker image tagging to all components one

### PR DESCRIPTION
**Pull request by nhaumont**
**What is the current behavior?** (You can also link to an open issue here)

The simple rest imaged is tagged with the docker version

**What is the new behavior?**

Get the same type of tagging as the "all components" image with the project version and timestamp

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1493/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1493/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Anhaumont%2FDEVOPS-3524%2Fautomate-publishing-of-tcomp-image)

**Comment by sgandon** [comment]
the docker build fails
`mvn clean install -DskipTests -Pdocker`

I have this error
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.20.1:build (start) on project components-api-service-rest: Execution start of goal io.fabric8:docker-maven-plugin:0.20.1:build failed: Given Docker name 'registry.datapwn.com/talend/tcomp-components-api-service-rest-local:0.21.0-SNAPSHOT-2017-12-13T17:20:13Z' is invalid:
[ERROR]    * tag part '0.21.0-SNAPSHOT-2017-12-13T17:20:13Z' doesn't match allowed pattern '^[\w][\w.-]{0,127}$'
```

**Comment by nhaumont** [comment]
The `mvn clean install -DskipTests -Pdocker` is succesful on my side and the images are properly created.

It seems that on your env, the `maven.build.timestamp` gives a different results than on my laptop and on the CI, but it should have been already the case for the all-components build

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1496/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1496/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Anhaumont%2FDEVOPS-3524%2Fautomate-publishing-of-tcomp-image)

**Comment by sgandon** [comment]
this works fine now, thanks

**Pull request merged**
