### PR TITLE
feat (TCOMP-256): add a dataset and datastore runtime interface

### PR DESCRIPTION
**Pull request by sgandon**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
2 new interfaces have bee added to cope with TDF requirements. DatastoreRuntime and DatasetRuntime.
I have also renamed the ComponentRuntime parent class because it is a parent for all Runtimable entities not only components.

**Does this PR introduce a breaking change?**
- [x] No
The class renamed above should not be used in any components yet.

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/125/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/125/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/133/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/133/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/136/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/136/)

**Comment by sgandon** [comment]
@RyanSkraba I have done the changes that we mentioned and also made the RuntimeableRuntime generic, it has an impact on all component I thus updated the version of the *components-api* module. The push will come soon, can you review it please?

**Comment by RyanSkraba** [comment]
Hey there!  As far as I know, we can merge this PR by removing the getPossibleDatasetNames and getEndpointSchema from the DataxxxRuntime interfaces :)  These methods are still kind of vague but we hope to get this clarified with Stefan's visit to Suresne next week.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/327/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/327/)

**Pull request merged**
