### PR TITLE
chore(TCOMP-1288): Java11 support

### PR DESCRIPTION
**Pull request by rmannibucau**
**What is the current behavior?** (You can also link to an open issue here)

Java 11 is not supported

**What is the new behavior?**

Java11 is supported

** Notes

1. Spark+paxexam tests were disabled until the support is native (spark 2.4.0 - last release today - is still using asm6 and not 7 as on their master).
2. IT got an implicit disablement when configuration (credentials) were not provided to enable to build OOTB

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/105/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/105/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/106/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/106/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/107/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/107/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/108/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/108/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/109/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/109/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/110/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/110/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/112/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/112/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/113/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/113/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/114/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/114/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/115/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/115/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/116/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/116/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/117/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/117/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/118/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/118/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/119/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/119/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/120/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/120/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/121/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/121/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/122/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/122/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/123/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/123/)

**Comment by rmannibucau** [comment]
Seems the build passed but sonar/jacoco is too old on the CI

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/125/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/125/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Armannibucau%2Fjava11-support)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/126/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/126/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Armannibucau%2Fjava11-support)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/129/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/129/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/29/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/29/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/30/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/30/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/31/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/31/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/32/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/32/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Armannibucau%2Fjava11-support)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/33/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/33/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Armannibucau%2Fjava11-support)

**Comment by wwang-talend** [comment]
revert something for netsuite as it can't pass the test in java 8 env which is the same env in jenkins. And will check it later in java 11.

**Comment by rmannibucau** [comment]
From the log the missing dep + linked bundle in the test is:

    <dependency>
        <groupId>org.apache.geronimo.specs</groupId>
        <artifactId>geronimo-osgi-locator</artifactId>
        <version>1.1</version>
    </dependency>

Worth not reverting but fixing that probably until we have a java 11 CI - i tested the full build locally for java 11 compliancy

**Comment by wwang-talend** [comment]
thanks  @rmannibucau, add back for netsuite, now should works

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/34/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/34/)

**Comment by wwang-talend** [comment]
the last failed is caused by env, so ignore it

**Pull request merged**
