### PR TITLE
feat(TDI-40684) : Snowflake support on Azure backport

### PR DESCRIPTION
**Pull request by ypiel-talend**
**What is the current behavior?** (You can also link to an open issue here)
(Backport from https://github.com/Talend/components/pull/1313)
https://jira.talendforge.org/browse/TDI-40662

**What is the new behavior?**
We can now select the provider 'AWS' or 'AZURE'. If azure is selected we can select the region.

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/113/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/113/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/16/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/16/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/22/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/22/)

**Comment by ypiel-talend** [comment]
Fail on ci with error : "Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.test.web.client.TestRestTemplate': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/apache/http/protocol/HttpContext"
Success on local. I merge.

**Pull request merged**
