### PR TITLE
TUP-4585: Backport TDI-35282 on new Framework

### PR DESCRIPTION
**Pull request by jzhao-talend**
https://jira.talendforge.org/browse/TUP-4585
Note:Support lookup field null value update

### CODE REVIEW

**Comment by jzhao-talend** [comment]
Need merge together with https://github.com/Talend/tdi-studio-se/pull/494

**Comment by jzhao-talend** [comment]
I can't find way to add junit test the runtime of upsert relationship table with default modules.
So only add a talend test job (export from 6.1.1)
https://jira.talendforge.org/secure/attachment/99835/TestCase_tSalesforceOutput_upsert_relationship.zip

**Comment by francisu** [comment]
@jzhao-talend what's the issue with being able to test it with Junit? We need to have all of the tests be done through the Junit mechanism here. We cannot rely on the studio tests.

**Comment by jzhao-talend** [comment]
@francisu 
yes. studio test is only for component developer and QA. Please ignore that.
My studio job is work with a customer module which was created in my salesforce account.
I don't know the relationship mapping with the default modules with default fields(Account/User/...)

**Pull request merged**
