### PR TITLE
Feature/6.3/tdi 37973 split jdbc module

### PR DESCRIPTION
**Pull request by wwang-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-37973

**What is the new behavior?**
split the jdbc component to definition and runtime

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:
https://jira.talendforge.org/browse/TDI-37973

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/219/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/219/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/221/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/221/)

**Comment by wwang-talend** [comment]
the conflict is not easy to fix...

**Comment by wwang-talend** [comment]
will create another branch and use the diff to fix the conflict

**Comment by sgandon** [comment]
I am fixing the conflict

**Comment by wwang-talend** [comment]
get it, thanks, Seb.

**Pull request merged**
