### PR TITLE
fix(TCOMP-330): change version of org.json:json to 20131018

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

Component depends on org.json:json:20090211

**What is the new behavior?**

Component depends on org.json:json:20131018

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Related to https://jira.talendforge.org/browse/TCOMP-330

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/848/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/848/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/935/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/935/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1035/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1035/)

**Comment by sgandon** [comment]
What bothers me is that you are only fixing the pb for salesforce, but if other components want to use OAuth, they will face the same pb. Isn't there another way to globally fix this ?

**Comment by sgandon** [comment]
I have tried to add this version in the <dependencyManagement/> of the pom in *components-parent* and it seems to work the same way, but it would also fix new Components using OAuth.
Could you check please?

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1074/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1074/)

**Comment by gonchar-ivan** [comment]
Failed tests related to Snowflake component. I think it's not related to current change

**Pull request merged**
