### PR TITLE
fix(TCOMP-352): exclude system scope from dependencies list generated…

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

tools dependency is present in dependencies.txt file for components

**What is the new behavior?**

tools dependency is excluded from dependencies.txt file for components

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Related to https://jira.talendforge.org/browse/TCOMP-352

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/757/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/757/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/808/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/808/)

**Comment by sgandon** [comment]
this is dangerous to only include compilation dependencies, today when returning the depenecies required for a component we just exclude the *test* scope but all other scope are included like * provided* and *runtime*. I would really suggest you only exclude *system* and *test*

**Comment by sgandon** [comment]
LGTM, when the build status are ok you can merge.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/811/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/811/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/813/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/813/)

**Pull request merged**
