### PR TITLE
chore(docker) : add memory and jmx env vars

### PR DESCRIPTION
**Pull request by amarouni**
**What is the current behavior?** (You can also link to an open issue here)
No easy way to change Xmx or add additional java options for the TCOMP docker image

**What is the new behavior?**
Add env vars that open the memory and java options for the TCOMP docker image

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [x] Other... Please describe: chore

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1704/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1704/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Achore%2Fjmx_docker)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1708/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1708/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Achore%2Fjmx_docker)

**Comment by amarouni** [comment]
@sgandon I added the `JAVA_OPTS` environment variable and removed the hardcoded 2G Xmx. If the user wants to limit the Xmx they'll have to export the `JAVA_OPTS` with the desired Xmx value.

@RyanSkraba The `.bat` file uses already the `JAVA_OPTS`

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1711/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1711/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Achore%2Fjmx_docker)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1712/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1712/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Achore%2Fjmx_docker)

**Pull request merged**
