### PR TITLE
chore(TDI-38134): avoid test failed in SalesforceSessionReuseTestIT.testUseExistingConnection

### PR DESCRIPTION
**Pull request by jzhao-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

SalesforceSessionReuseTestIT.testUseExistingConnection() test failed randomly 
I guess the session is not disabled in some situation.

**What is the new behavior?**

Move the faild part into try catch behind `invalidSession(connProps, null);`

**Does this PR introduce a breaking change?**

- [x] No

**Other information**:
https://jira.talendforge.org/browse/TDI-38134

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/713/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/713/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/881/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/881/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/918/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/918/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/919/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/919/)

**Comment by jzhao-talend** [comment]
@sgandon 
I have push new commits to ignore 2 tests `testUseExistingConnection()` and `testOutputReuseSession()` which failed randomly. But can't find a good way to fix it.
I can't reproduced that in my local side.

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/923/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/923/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/928/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/928/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/929/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/929/)

**Comment by sgandon** [comment]
@jzhao-talend LGTM, you can merge it whenever you want.

**Pull request merged**
