### PR TITLE
chore: Update fabric8 docker plugin to use one version.

### PR DESCRIPTION
**Pull request by RyanSkraba**
**What is the current behavior?** (You can also link to an open issue here)

We use three different versions of docker-maven-plugin and ignore the version set in the components-parent pom.xml.

We've been getting odd errors from CI in general around this plugin and how it fetches images, and it looks like it works with the newer release.

**What is the new behavior?**

We use a recent version of docker-maven-plugin across all components modules.

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/3/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/3/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/4/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/4/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/6/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/6/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/7/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/7/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/8/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/8/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/9/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/9/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/10/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/10/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/11/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/11/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Arskraba%2Fchore%2Fupdate-fabric8)

**Comment by RyanSkraba** [comment]
ci-commons tests on Salesforce fail, look unrelated to this PR.

**Pull request merged**
