### PR TITLE
fix(TDI-44413): fix big date values

### PR DESCRIPTION
**Pull request by mbasiuk-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-44413

This issue happened in tSnowflakeOutputBulk, but the root is in the SnowflakeWriter. 
Refecatored JUnits, to avoid put credentials in connection String.

**What is the new behavior?**
Date values will be formatted, to avoid usage of long values.

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [x] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/403/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/403/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/404/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/404/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/405/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/405/)

**Comment by mbasiuk-talend** [comment]
Latest build:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Components - Snowflake Definition .................. SUCCESS [04:57 min]
[INFO] Components - Snowflake Runtime ..................... SUCCESS [ 36.610 s]
[INFO] Components - Snowflake Integration Tests ........... SUCCESS [04:44 min]
[INFO] Components - Snowflake Aggregator .................. SUCCESS [  0.208 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

https://ci-common.datapwn.com/job/components_pull-request_master/405/console

**Pull request merged**
