### PR TITLE
feature/allow-docker-tagging-in-CI

### PR DESCRIPTION
**Pull request by jleloup**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

Current TCOMP REST API docker images are tagged using Maven internal values unavailable from Jenkins standpoint.
This should be updated according to https://jira.talendforge.org/browse/DEVOPS-2167

**What is the new behavior?**

A new property called "docker_tag_suffix" is available for CI to provide a deterministic value that can be used later on during post-build to push Docker images in the registry.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/44/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/44/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/45/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/45/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/46/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/46/)

**Comment by sgandon** [comment]
Could you then remove the *docker.version* property and it's computation from all the scripts please ?

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/47/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/47/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/48/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/48/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/49/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/49/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/6/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/6/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/5/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/5/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/65/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/65/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/66/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/66/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/64/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/64/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/67/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/67/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/68/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/68/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/69/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/69/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/70/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/70/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/72/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/72/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/3/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/3/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/6/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/6/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/12/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/12/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/24/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/24/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/25/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/25/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/26/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/26/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/83/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/83/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/102/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/102/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/104/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/104/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/107/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/107/)

**Pull request merged**
