### PR TITLE
Dsylaiev/tdi 39312 move marklogic to tcomp

### PR DESCRIPTION
**Pull request by dmytro-sylaiev**
**What is the current behavior?** (You can also link to an open issue here)
MarkLogic is javajet component family

**What is the new behavior?**
MarkLogic moved to tcomp

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) ?
- [x] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1567/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1567/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Adsylaiev%2FTDI-39312_move_marklogic_to_tcomp)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1600/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1600/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1601/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1601/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1602/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1602/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1603/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1603/)

**Comment by dmytro-sylaiev** [comment]
JDBC tests are failing but not jdbc impact in this pull request.

**Pull request merged**
