### PR TITLE
TDI-36929: fix the jar conflict for salesforce and dataprep in new fr…

### PR DESCRIPTION
**Pull request by wwang-talend**
…amework

https://jira.talendforge.org/browse/TDI-36929

### CODE REVIEW

**Comment by wwang-talend** [comment]
the test case fail because : REQUEST_LIMIT_EXCEEDED , so will rerun it tomorrow.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/168/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/168/)

**Comment by tsteinborn** [comment]
why did we exceed the limit? Salesforce allows up to 1000 calls per api a day. So where are we spending all these API calls?

**Comment by sgandon** [comment]
@wwang-talend , do we still have the pb because since the time of this PR the parent changed a bit ?

**Comment by wwang-talend** [comment]
will check it later.

**Comment by wwang-talend** [comment]
now we can run the junit case in the ide like eclipse, no need to change the pom, so we can close it now.

**Pull request closed without merging**
