### PR TITLE
chore(TCOMP-447): test performance plugin

### PR DESCRIPTION
**Pull request by chmyga**
* Add running performance test to check performance plugin on jenkins.

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
Performance test should run and create the .xml report file, which should be analyzed by performance plugin and results must be published to jenkins.

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1019/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1019/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1025/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1025/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1030/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1030/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1041/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1041/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1044/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1044/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1048/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1048/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1193/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1193/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1203/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1203/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1260/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1260/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1262/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1262/)

**Comment by gonchar-ivan** [comment]
not valid anymore

**Pull request closed without merging**
