### PR TITLE
Feature/TCOMP-318 package rest service

### PR DESCRIPTION
**Pull request by sgandon**
- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
web service was just the definitions package into on jar

**What is the new behavior?**
the web service is packaged with the runtime maven repository along with linux and windows start and stop scripts to launch the service.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by vjaouen** [comment]
I see 2 bugs with this packaging : 
* the log4j2.xml file is not used (hence you cannot set the logs up)
* I have an error while creating a JDBC datastore (BAD_DATASTORE_CONNECTION:{messages=org.gjt.mm.mysql.Driver}) (maybe the driver class is not found ?)

**Comment by sgandon** [comment]
ok thanks I'll check

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/165/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/165/)

**Comment by sgandon** [comment]
I have create a jira for the jdbc issue. https://jira.talendforge.org/browse/TDI-37973

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/195/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/195/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/211/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/211/)

**Pull request merged**
