### PR TITLE
Update readme of `components-api-service-rest-all-components`

### PR DESCRIPTION
**Pull request by sim51**
Correct markdown formatting

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/826/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/826/)

**Comment by gonchar-ivan** [comment]
Thank you very much for PR!

**Comment by gonchar-ivan** [comment]
@sim51 could you please get acquainted with our contributing policy
https://github.com/Talend/tools/blob/master/tools-root-github/CONTRIBUTING.md
and fix commit message

**Comment by sim51** [comment]
Done !

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/841/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/841/)

**Comment by gonchar-ivan** [comment]
Nice! Thank you very much!

**Pull request merged**
