### PR TITLE
fix(TDI-38133): Problems with Snowflake date type conversion

### PR DESCRIPTION
**Pull request by chmyga**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Date type fields were sent to the snowflake db incorrectly, what was leading to wrong results.
https://jira.talendforge.org/browse/TDI-38141
https://jira.talendforge.org/browse/TDI-38133

**What is the new behavior?**
Date/Time/Timestamp fields are formatted correctly, values are sent and retrieved from database correctly.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by sgandon** [comment]
One thing that bothers me here is that I don't see any new Unit tests. But if there was an issue the old ones could not show the issues so I would guess you need new Unit test that would fails without your fix and pass with your fixes in this PR.
What do you think ?

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/821/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/821/)

**Comment by chmyga** [comment]
It was related more to the correctness of passed data. It's more like an inner refactoring. Also, already existing tests weren't using the correct values. This fix fixed the tests and the code was changed quite a lot in order to pass the already existing tests. New tests won't let us reproduce the old problems using the correct schema. the only possible way I see here is using an incorrect schema, but would that be a correct test? It won't really show the fixed problems.

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/916/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/916/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/920/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/920/)

**Comment by chmyga** [comment]
The build is failed due to Salesforce connection test. This failure can occur randomly, which doesn't influence Snowflake component in any way.

**Pull request merged**
