### PR TITLE
fix(TDI-45223):upgrade zookeeper version.

### PR DESCRIPTION
**Pull request by vyu-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45223

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/551/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/551/)

**Review by wwang-talend — APPROVED** [review]

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/578/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/578/)

**Review by pyzhou-talend — CHANGES_REQUESTED** [review]
According to Pierre, zookeeper.version should be set in bom https://github.com/Talend/components/blob/master/components-parent/components-bom/pom.xml

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/579/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/579/)

**Review by pyzhou-talend — APPROVED** [review]

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/580/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/580/)

**Pull request merged**
