### PR TITLE
chore(TDI-44145): update commons-codec:1.14

### PR DESCRIPTION
**Pull request by ozhelezniak-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-44145

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard

**What kind of change does this PR introduce?**

- [x] Other... Please describe: CVE

**Does this PR introduce a breaking change?**

- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/486/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/486/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/489/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/489/)

**Comment by ozhelezniak-talend** [comment]
This PR should be postponed because it may produce a problem with unavailable commons-codec:1.14 dependency during the monthly patch

**Review by Voievidko — APPROVED** [review]
LGTM

**Comment by ozhelezniak-talend** [comment]
It can't be updated for a monthly patch due to Studio update behavior.

**Pull request closed without merging**
