### PR TITLE
Feature/tdi 38071 marketo

### PR DESCRIPTION
**Pull request by undx**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Warning: tMarketoConnection referenced by other components in Studio doesn't work properly.

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/5/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/5/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/6/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/6/)

**Comment by wwang-talend** [comment]
you forget to change here : https://github.com/Talend/components/blob/master/components/pom.xml

**Comment by wwang-talend** [comment]
seems now no marketo env var in our test env, so not sure the marketo test can be passed, maybe we need to ignore all the runtime tests(even all) fisrtly.

**Comment by wwang-talend** [comment]
i push a commit to register the marketo module and ignore all the IT tests as we have no marketo env.

**Comment by wwang-talend** [comment]
a minor thing : connectionWizardIcon.png and another one is a little big if you see it in the studio.

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/10/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/10/)

**Comment by wwang-talend** [comment]
MarketoRuntimeInfoTest test should be put to a integration test module which run after the marketo module. Now i may only ignore it easily.

**Comment by wwang-talend** [comment]
about definition part, LGTM, and about the runtime part, i find you don't use AvroRegistry like others, not sure if it's good, we can discuss it later, now LGTM.

**Comment by gonchar-ivan** [comment]
Yes it is good to not use AvroRegistry. It is planned to remove this interface at all.

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/11/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/11/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/12/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/12/)

**Pull request merged**
