### PR TITLE
feat(TCOMP-476): Create component service based on Java SPI.

### PR DESCRIPTION
**Pull request by RyanSkraba**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

You must use OSGi or Spring to discover registered components.

**What is the new behavior?**

A lightweight ComponentService provider based on the Java SPI extension mechanism.  Definition modules must add a configuration file in their resources to activate component installation.  Only `localio-definition` and `simplefileio-definition` were modified here.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

This is one alternative for implementing TCOMP-476

### CODE REVIEW

**Comment by sgandon** [comment]
nice.

**Comment by sgandon** [comment]
and simple ;)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/901/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/901/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/903/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/903/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/917/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/917/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/937/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/937/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/938/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/938/)

**Pull request merged**
