### PR TITLE
fix(TDI-36749): add the space for the display name for one button

### PR DESCRIPTION
**Pull request by wwang-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-36749

**What is the new behavior?**
add the space for the display name

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:
https://jira.talendforge.org/browse/TDI-36749

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/990/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/990/)

**Comment by pteyssier** [comment]
Doesn't work for old job but too minor to write a migration task here.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/993/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/993/)

**Comment by wwang-talend** [comment]
the pull-request-to-master test fail as another reason, not about the current fix.

**Comment by sgandon** [comment]
Yes I am looking into it. see https://github.com/Talend/daikon/pull/101

**Pull request merged**
