### PR TITLE
Feature/6.4.1/tdi 38096 salesforce pk chunking

### PR DESCRIPTION
**Pull request by mbasiuk-talend**
**What is the current behavior?** (You can also link to an open issue here)
Currently can not use primary key chunking for large volumes of data in Salesforce.
https://jira.talendforge.org/browse/TDI-38096

**What is the new behavior?**
Add possibility to setup primary key chunking for Salesforce bulk connection.
Chunk size must be less than 250000. This feature should be used for volumes greater than 20 M records
[Official documentation](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/async_api_headers_enable_pk_chunking.htm)

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/257/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/257/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/278/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/278/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/281/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/281/)

**Comment by gonchar-ivan** [comment]
Builds are failed for the following reason.
Last master build was 5 days ago on the 28 of Apr
components-osgitest in nexus repository is outdated.
For some reason org.talend.components-components-api-service-osgi-tests.link file points not to latest version, but to the concrete version:
mvn:org.talend.components/components-api-service-osgi/0.18.0-20170428.122019-117//tests
But this version was already removed from nexus repository.

I've rebuilt components-osgitest locally. And restarted tests locally. They passed, however they failed before too.
Thus, we need master rebuild to fix this build

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/286/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/286/)

**Pull request merged**
