### PR TITLE
fix(copyright-year): make the copyright year automated in eclipse

### PR DESCRIPTION
**Pull request by akhabali**
**What is the current behavior?** (You can also link to an open issue here)
year is hard coded into the copyright

**What is the new behavior?**
make the year auto generated in eclipse

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/401/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/401/)

**Comment by gonchar-ivan** [comment]
Seems, tooling directory is not official any more. However, we may change it.
https://github.com/Talend/tools/blob/master/tools-java-formatter/src/main/resources/codetemplates.xml
This one is official.

**Comment by akhabali** [comment]
i don't have sufficient rights to push a PR on the Talend/tools repository 
If this tooling folder is not official any more. we should remove it i think, @sgandon

**Comment by gonchar-ivan** [comment]
ok. However we may create PR via forked repository.
I prepared PR for it. https://github.com/Talend/tools/pull/41

**Pull request merged**
