### PR TITLE
feat(TFD-472): Add FilterColumn.

### PR DESCRIPTION
**Pull request by pbailly**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
Add a new processing component: the FilterColumn

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/727/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/727/)

**Comment by sgandon** [comment]
@pbailly what is the status of this PR ?

**Comment by pbailly** [comment]
I was waiting review on https://github.com/Talend/components/pull/463 before the merge this one.
The PR 463 contains a library that was started on this components and lot of works was made to make it more efficient and generic.
However, if we need this components, this PR can be merged as a standalone.

**Comment by pbailly** [comment]
Do *not* delete this branch, this is going to be reworked on the next sprint.

**Comment by pteyssier** [comment]
PR and branch are 2 different things. It's been 2 months you said it will be reworked in next sprint...

**Pull request closed without merging**
