### PR TITLE
fix(TDI-45311):upgrade guava version.

### PR DESCRIPTION
**Pull request by vyu-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45311

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/592/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/592/)

**Review by pyzhou-talend — APPROVED** [review]
LGTM

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/620/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/620/)

**Review by pyzhou-talend — APPROVED** [review]

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/621/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/621/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/622/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/622/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/623/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/623/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/624/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/624/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/625/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/625/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/626/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/626/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/627/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/627/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/628/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/628/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/629/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/629/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/630/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/630/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/631/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/631/)

**Pull request merged**
