### PR TITLE
fix(TDI-46283): AzurePut filemask

### PR DESCRIPTION
**Pull request by ozhelezniak-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-46283

**What is the new behavior?**
Added a new checkbox in advanced settings. It allows as to escape plus symbol in filemask for tAzureStoragePut component

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard

**What kind of change does this PR introduce?**

- [x] Bugfix

**Does this PR introduce a breaking change?**

- [x] Yes

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/819/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/819/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/829/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/829/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/830/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/830/)

**Review by undx — APPROVED** [review]
LGTM

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/835/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/835/)

**Pull request merged**
