### PR TITLE
Align Docker image version with policy

### PR DESCRIPTION
**Pull request by rdalverny**
**What is the new behavior?**
Docker image version is aligned with our new policy.

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [x] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**
Build / CI related changes.
See: https://jira.talendforge.org/browse/DEVOPS-5343

**Does this PR introduce a breaking change?**
No.

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/99/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/99/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3ADEVOPS-5343-align-docker-version-policy)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/100/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/100/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3ADEVOPS-5343-align-docker-version-policy)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/101/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/101/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3ADEVOPS-5343-align-docker-version-policy)

**Comment by rdalverny** [comment]
Sorry I didn't squash... :/ went too fast.

**Pull request merged**
