### PR TITLE
Enable CITIZEN_USER form for TCOMP rest api & JDBCDatastore

### PR DESCRIPTION
**Pull request by vjaouen**
**Please check if the PR fulfills these requirements**
- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When querying component properties via the REST API, there's no way to query a specific form.

**What is the new behavior?**
TCOMP REST API endpoints now have an optional parameter : formName. The default value is "Main", if it's not specified.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://jira.talendforge.org/browse/TDKN-110

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/175/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/175/)

**Comment by francisu** [comment]
@vjaouen maybe you can have the default for the form be null and the Form.MAIN can be done in the Daikon code? I think it might be better at that level. I think we want as few semantics as possible at the server level. WDYT?

**Comment by vjaouen** [comment]
@francisu I am not found of null Strings. Anyway, let's not spend too much time on this, I'll do the changes you suggest.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/179/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/179/)

**Comment by sgandon** [comment]
don't worry about the merged build failing, it never works on branches requiring daikon branch.
see https://jira.talendforge.org/browse/DEVOPS-1432

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/183/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/183/)

**Pull request merged**
