### PR TITLE
fix(TDI-39682): add the multi line flag for the query property

### PR DESCRIPTION
**Pull request by wwang-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-39682

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1396/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1396/)

**Comment by wwang-talend** [comment]
build failed sure as it depend one changeset on daikon

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1397/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1397/)

**Comment by wwang-talend** [comment]
Build failed as some other issue, not caused by current fix : 
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/components_pull-request_master/components/services/components-api-service-osgi/src/main/java/org/talend/components/api/service/internal/osgi/ComponentServiceOsgi.java:[36,44] package org.talend.daikon.properties.runtime does not exist
[ERROR] /var/lib/jenkins/workspace/components_pull-request_master/components/services/components-api-service-osgi/src/main/java/org/talend/components/api/service/internal/osgi/ComponentServiceOsgi.java:[112,80] cannot find symbol
  symbol:   class RuntimeContext
  location: class org.talend.components.api.service.internal.osgi.ComponentServiceOsgi

**Pull request merged**
