### PR TITLE
refactor(TCOMP-249): reorganize folders

### PR DESCRIPTION
**Pull request by sgandon**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
many folder where at the root of the repo causing mess and confusion.

**What is the new behavior?**
moved components-api to core
removed webtest, replaced by service/component-api-service-rest
moved components-api-full-example to examples
moved components-api-proptester to core
moved all components modules to components
moved osgi-test to core
removed generate-p2-repo cause not used
update the readme after refactoring root folders

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/640/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/640/)

**Comment by RyanSkraba** [comment]
Awesome! The tree structure looks great :)

Can you move `components-common*` to `core`, as part of the component development SDK?  Ideally, modules in the `component` subdirectory should not depend on each other (I'm thinking that we might be able to improve the build process if we keep this property!)

**Comment by sgandon** [comment]
done my friend :)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/644/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/644/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/645/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/645/)

**Comment by RyanSkraba** [comment]
LGTM!  Thanks!

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/655/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/655/)

**Pull request merged**
