### PR TITLE
[TFD-710] Use Beam 0.6.0-tlnd-SNAPSHOT

### PR DESCRIPTION
**Pull request by jbonofre**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

FileIO component doesn't compile.

**What is the new behavior?**

FileIO compiles again thanks to the Talend Beam version.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/146/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/146/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/155/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/155/)

**Comment by jbonofre** [comment]
Checking when tests are failing.

**Comment by RyanSkraba** [comment]
Tested on jenkins as part of https://ci-common.datapwn.com/job/components_pull-request_master/178/console

**Pull request merged**
