### PR TITLE
feat(TDI-35748):salesforce connection save and reuse session

### PR DESCRIPTION
**Pull request by jzhao-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

https://jira.talendforge.org/browse/TDI-35748
1) Implement the reuse session funcation which we didn't do in 6.2.1
2) Fix bulk connection session renew doesn't work

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [x] No

### CODE REVIEW

**Comment by jzhao-talend** [comment]
Notice:
The merge build test passed. 
https://ci-common.datapwn.com/job/components_pull-request_master/457/
But set pull request label fails:
https://ci-common.datapwn.com/job/set_github_pull_request_status/167/console

**Comment by jzhao-talend** [comment]
Would be backport to maintenance 0.13 firstly.

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/649/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/649/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/666/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/666/)

**Pull request merged**
