### PR TITLE
fix(TDI-39544): Import salesforce with oauth type can't show my value

### PR DESCRIPTION
**Pull request by akhabali**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-39544

**What is the new behavior?**
fix the migration task

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1425/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1425/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1428/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1428/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1431/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1431/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1432/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1432/)

**Comment by pteyssier** [comment]
That's not a migration task here, it's a test in the code implementation about the version.

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1448/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1448/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1465/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1465/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1467/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1467/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1468/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1468/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1469/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1469/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1474/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1474/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1480/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1480/)

**Comment by akhabali** [comment]
closed and reopened with the same daikon fix branch name for the ci build in
https://github.com/Talend/components/pull/1069

**Pull request closed without merging**
