### PR TITLE
TDI-37479 Added percent type schema infering

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
SalesforceAvroRegistry returns String schema for Percent Salesforce specific data type

**What is the new behavior?**
SalesforceAvroRegistry returns Double schema for Percent Salesforce specific data type

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Related to https://jira.talendforge.org/browse/TDI-37479

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/118/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/118/)

**Comment by francisu** [comment]
Why is percent expressed as a double? Wouldn't it be better as a decimal value? In general floating point is not used for commerce things like this (but maybe this is the way it's implemented in salesforce).

**Comment by gonchar-ivan** [comment]
@sgandon,
I've added test-case
see SalesforceAvroRegistryTest.java

@francisu,
2 reasons for it:
1. It is a way it's implemented in Salesforce 
https://developer.salesforce.com/docs/atlas.en-us.200.0.object_reference.meta/object_reference/field_types.htm
see percent type

2. Backward compatibility. Old (javajet) Salesforce treated percent as double type.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/168/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/168/)

**Pull request merged**
