### PR TITLE
fix(TCOMP-330): fix jackson, junit, jetty dependencies

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

Dependencies versions are wrong

**What is the new behavior?**

Fixed dependencies versions

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Related to https://jira.talendforge.org/browse/TCOMP-330
Was broken in this commit
https://github.com/Talend/components/commit/5bb13c68828da05293fb0f7c4decd424110e227b#diff-8f997edf0285283955e4c6e1f279a3ecR64

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/671/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/671/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/673/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/673/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/685/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/685/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/716/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/716/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/718/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/718/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/719/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/719/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/722/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/722/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/723/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/723/)

**Comment by gonchar-ivan** [comment]
Fixed by Seb here https://github.com/Talend/components/pull/309

**Pull request closed without merging**
