### PR TITLE
fix(TDI-40154): adjust Snowflake JDBC Parameters for dataprep platform

### PR DESCRIPTION
**Pull request by wwang-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-40154

**What is the new behavior?**
https://jira.talendforge.org/browse/TDI-40154

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1734/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1734/)

**Comment by wwang-talend** [comment]
https://ci-common.datapwn.com/job/components_comp_wwang-talend_TDI-40154/

**Comment by wwang-talend** [comment]
the test failed as some network issue, not about current fix

**Comment by wwang-talend** [comment]
Now there is some issue in the build and test process in jenkins, we will merge this directly as it's a small fix and safe.

**Comment by wwang-talend** [comment]
https://ci-common.datapwn.com/job/components_wwang-talend_TDI-40154/3/

**Pull request merged**
