### PR TITLE
chore(build): Specify snapshot and release repositories

### PR DESCRIPTION
**Pull request by iwangtalend**
**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/993/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/993/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/994/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/994/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/995/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/995/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/996/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/996/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/997/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/997/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/998/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/998/)

**Comment by RyanSkraba** [comment]
I can't figure out why the build is breaking on org.talend.components.simplefileio.runtime.s3.S3RoundTripRuntimeTestIT.testAvro_sseKmsEncryption

I relaunched the build to see if this is just a flaky result and it seems to have gotten past this test.  It also works locally (with my local S3 credentials).

https://ci-common.datapwn.com/job/components_pull-request_master/1006/

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1006/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1006/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1014/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1014/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1020/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1020/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1023/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1023/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1026/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1026/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1027/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1027/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1033/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1033/)

**Pull request merged**
