### PR TITLE
fix(TFD-601): Reactivate S3 integration tests.

### PR DESCRIPTION
**Pull request by RyanSkraba**
**What is the current behavior?** (You can also link to an open issue here)

S3 IT were deactivated until credentials were added to CI.

**What is the new behavior?**

S3 IT are reactivated

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/256/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/256/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/272/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/272/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/331/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/331/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/485/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/485/)

**Comment by gonchar-ivan** [comment]
This change was done here https://github.com/Talend/components/pull/874
So, I am closing this PR

**Pull request closed without merging**
