### PR TITLE
Simple version of tDataStewardshipTaskOutput and tDataStewardshipCampaignOutput

### PR DESCRIPTION
**Pull request by lpw82gf**

### CODE REVIEW

**Comment by glzhou** [comment]
We should have junit test.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/205/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/205/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/207/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/207/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/208/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/208/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/209/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/209/)

**Comment by glzhou** [comment]
OK to merge

**Pull request merged**
