### PR TITLE
refactor: Build 'slow' components last.

### PR DESCRIPTION
**Pull request by RyanSkraba**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

The salesforce component takes a long time to build, and it built before all of the other components.

**What is the new behavior?**

Salesforce and snowflake were "pushed" as the last components to be built, so that other components have the opportunity to "fail fast" if errors occur.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1001/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1001/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1005/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1005/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1010/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1010/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1047/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1047/)

**Comment by sgandon** [comment]
@Ryan what is the status of this PR ? can you merge it ?

**Comment by RyanSkraba** [comment]
@sgandon: It's diverged too far from master, so I fixed and push --forced it.  If the build succeeds, it's mergeable!

**Comment by sgandon** [comment]
excellent, please merge it then once the build is ok.

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/29/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/29/)

**Pull request merged**
