### PR TITLE
fix(TDI-44498): change reduntant property name

### PR DESCRIPTION
**Pull request by mbasiuk-talend**
**What is the current behavior?** (You can also link to an open issue here)
Allow Snowflake to convert columns and tables to uppercase (Note: Unquoted identifiers should match the Snowflake Identifier Syntax.)
Disinforms users of actual property meaning.

**What is the new behavior?**
We can use quoted objects in query or unquoted. Unquoted by default

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/442/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/442/)

**Comment by wwang-talend** [comment]
after a more check, i think the change for tsnowflakeoutput is a little dangerous, as we have some code to use the db name to do match action in snowflakewriter class like this :
https://github.com/Talend/components/blob/maintenance/0.28/components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java#L354-L359

so could we not change tsnowflakeoutput now, we can do it later more carefully, current jira only for input

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/443/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/443/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/444/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/444/)

**Pull request merged**
