### PR TITLE
Bug/6.3/tdi 37635

### PR DESCRIPTION
**Pull request by wwang-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
please see the comment in https://jira.talendforge.org/browse/TDI-37635.
adjust the tdataprepdbinput component to meet the requirement of https://jira.talendforge.org/browse/TCOMP-344

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:
https://jira.talendforge.org/browse/TDI-37635
https://jira.talendforge.org/browse/TCOMP-344

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/566/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/566/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/572/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/572/)

**Comment by wwang-talend** [comment]
need to rebase to the master

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/583/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/583/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/634/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/634/)

**Comment by wwang-talend** [comment]
seem need to rebase to master.

**Comment by wwang-talend** [comment]
done : rebase to master

**Comment by wwang-talend** [comment]
https://github.com/Talend/components/pull/295

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/656/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/656/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/658/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/658/)

**Comment by wwang-talend** [comment]
rebase to master

**Comment by wwang-talend** [comment]
after doing the action :
1. rebase my local branch to origin/master after a fetch all 
2. call git push --force-with-lease 37635 origin/37635
then no build and test information for the pull-merged-to-master branch, need to fix it.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/660/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/660/)

**Comment by wwang-talend** [comment]
i will create new dev branch and pull request to avoid the jenkins and github status issue .

**Pull request closed without merging**
