### PR TITLE
TMDM-9962 : [DI] TDS - tDataStewardshipTaskInput - Back-end of compon…

### PR DESCRIPTION
**Pull request by lpw82gf**
…ent (fix TDS_SCORE column type issue)

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/367/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/367/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/368/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/368/)

**Comment by sgandon** [comment]
I don't see any unit test for this change ?

**Comment by lpw82gf** [comment]
The method is just a static method to return static data. This change is really a small fix to make it work with the logic in CampaignAvroRegistry.java. I wrote the code wrongly at the beginning and now I realized and fix it, I don't see the point to write test case for this kind change.

**Pull request closed without merging**
