### PR TITLE
Bugfix/tdi 37873

### PR DESCRIPTION
**Pull request by francisu**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

https://jira.talendforge.org/browse/TDI-37873

**What is the new behavior?**

Component works in the studio

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/911/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/911/)

**Comment by sgandon** [comment]
checking the tests issues.

**Comment by sgandon** [comment]
OSGI tests are failing because you removed the `,com.snowflake*` from the export package command.
I think this cause not arm to export those API and will make the tests work. I also wonder if you are not required to export them to be used by the jdbc APIs.

**Comment by francisu** [comment]
OK, I fixed the export; The problem is the export causes the classes to be included in files inside of the Jar files; but the studio requires the actual Jar file. Both are now being included (at a cost of twice the size -- which is unfortunate, but at least everything will work).

**Pull request merged**
