### PR TITLE
feat(TFD-3568): Flatten Kafka datastore to triggers.

### PR DESCRIPTION
**Pull request by pbailly**
**What is the current behavior?** (You can also link to an open issue here)
Activating a trigger on a sub properties result into a crash of the serialization/deserialization of the JSONSchema API.

**What is the new behavior?**
Flatten Kafka Properties.

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features) ?
- [X] The code coverage on new code >75%
- [X] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [X] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
The kafka JSONSchema serialization had a hierarchy on the "ssl" property. The Hierarchy is flattened, so any existing JSONSchema  (ie: on an export or on a database) is going to be invalid.
You can easilly change the schema by hand by removing the hierarchy (For an example, please refer to https://github.com/Talend/data-streams-tools/pull/237 ) 

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1806/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1806/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Afix%2FTFD-3568_kafka_bad_gateway)

**Comment by RyanSkraba** [comment]
To be checked with component-runtime, but if I remember correctly, the _future_ of component properties is going to look a lot flatter than the hierarchical promise of daikon `Properties` (but still retain many of the advantages).

In the meantime, it's probably not worth investing in a fix in the current components API.  I don't like the idea of widespread copy/pasting like this but it's likely to be addressed when we migrate to 1.0

**Comment by RyanSkraba** [comment]
Checked with component-runtime, the persisted properties are flattened and reshaped into data objects.  The challenge of migration from components is likely to be simplified by flattening objects now.

**Comment by pbailly** [comment]
Chen Bin > This is require only when there is a trigger on your inner-property.
I did not see the PR with the required, I will integrate these changes. Thank you!

**Pull request merged**
