### PR TITLE
fix(TDI-36827): enable the chunk mode for tdatasetoutput

### PR DESCRIPTION
**Pull request by wwang-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-36827

**What is the new behavior?**
add the chunk support and check if the data set exists before creating it

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:
https://jira.talendforge.org/browse/TDI-36827

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/995/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/995/)

**Comment by wwang-talend** [comment]
the test fail because some other reason, not about the current fix

**Comment by gonchar-ivan** [comment]
Ok for me.
However, we are moving DataPrep to components-ee repo.
Could you please, to make this changes on component-ee repo.

**Comment by sgandon** [comment]
@wwang-talend can you close this if it need to be on *components-ee*

**Pull request merged**
