### PR TITLE
Add structure for new components-processing

### PR DESCRIPTION
**Pull request by StefanLMNG**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

No module for components-processing.

**What is the new behavior?**

Add "components-processing" module to have a base to add new components processing.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
An example on that kind of component will be added soon.

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/136/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/136/)

**Comment by pbailly** [comment]
LGTM (as soon as the build works)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/142/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/142/)

**Comment by francisu** [comment]
A small question: What is this for?

**Comment by pbailly** [comment]
Helll Francis,
We are several person to work on different processing components. This PR will allow us to make the futurs PR of the various processing components at our own rythme without deadlocking anyone.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/143/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/143/)

**Comment by francisu** [comment]
@pbailly Is a processing component the same as a transformation component (a "middle" component)? We should probably align on the right word for this in TCOMP.

**Comment by francisu** [comment]
@StefanLMNG there should be a JIRA associated with this.

**Comment by RyanSkraba** [comment]
Hello!  The relevant JIRA are all linked to https://jira.talendforge.org/browse/TFD-106

This first step is to enable the devs on these components to work at the same time in a component family.

I'm OK with renaming this to transformation.  Is this *the* accepted term?  To be honest, we've always distinguished transformation components as a subset of processing:

* a processing component is a "middle" component that *may* involve a repartitioning event on the data (like aggregate or sort),
* a transformation component is one that treat records individually and can be easily parallelized, like filter row, filter column, extract JSON, etc.  There is no repartition necessary.

**Comment by francisu** [comment]
@RyanSkraba processing seams reasonable as a replacement to what we have called transformation. I'm still not sure of the intent of this particular PR. Is it to be some kind of superclass for processing components? Or a category? I don't understand what this contributes to having the components be done in parallel. For connection components, we don't have a top-level category for all connection components.

**Comment by RyanSkraba** [comment]
@francisu : Sorry, I can see how this was misleading!    These two modules won't contain super classes and will not introduce API requirements for processing components!

This is literally the component family that will contain the basic processing components available via TCOMP like filter row and filter column.  Pierre and Stefan are each working on different components that will be added in this column family (filter row, filter column and stream window).

So there's only the maven module infrastructure in this PR and the ComponentFamilyDefinition that will *eventually* start to be populated with processing components (hopefully one PR per component), so they can work independently on their components.

**Comment by RyanSkraba** [comment]
Oops, one more thought -- it makes sense to me to have a "processing component family" that contains the  *basics*, but we could slice them up differently.  I can imagine that something like tMap or tHConvertIO would be better off in an individual family, not all in the same module as tFilterRow.

**Pull request merged**
