### PR TITLE
revert(TDI-38100) : reverted Campaign, Company and Opportunities for …

### PR DESCRIPTION
**Pull request by undx**
…6.4.1

**What is the current behavior?** (You can also link to an open issue here)

As discussed with @pteyssier, we will revert the functionalities in 6.4.1 for
https://jira.talendforge.org/browse/TDI-38100
It will be enabled after 6.4.1.

**What is the new behavior?**

Removed Campaign component, Company and Opportunities.

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/404/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/404/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/453/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/453/)

**Comment by jzhao-talend** [comment]
@undx why only part of code is reverted ? I found some code which only used in `Campaign, Company and Opportunities` is not be revert, like the modification:
[MarketoConstants.java    ](https://github.com/Talend/components/blob/8ac4fee04f4aa926d004a52202c1f7e867f8c51b/components/components-marketo/src/main/java/org/talend/components/marketo/helpers/TokenTable.java#L31-L31)             [   TokenTable.java](https://github.com/Talend/components/blob/1bc4973b130d697fcd094cb00d53f717b65520c2/components/components-marketo/src/main/java/org/talend/components/marketo/MarketoConstants.java#L509-L509)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/461/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/461/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/477/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/477/)

**Pull request merged**
