### PR TITLE
feat(TFD-1759): support kinesis

### PR DESCRIPTION
**Pull request by bchen-talend**
**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
new component for AWS Kinesis

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1475/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1475/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1481/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1481/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1501/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1501/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Abchen%2FTFD-1759-KinesisIO)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1536/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1536/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Abchen%2FTFD-1759-KinesisIO)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1554/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1554/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Abchen%2FTFD-1759-KinesisIO)

**Comment by bchen-talend** [comment]
Hi @undx 
Thanks for your review, I added `String[] getFamilies() and List<String> getSupportedProducts()` as you mentioned.
for IT test, the current idea is add definition dependency in `kinesis-integration` only, and check the runtime invoke is right.
and as Kinesis component runtime just a wrapper for Beam's KinesisIO, the mock test has been done on Beam side, and even there is no environment configured, the test can work with docker image only, and ignore these part of test.

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1558/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1558/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Abchen%2FTFD-1759-KinesisIO)

**Pull request merged**
