### PR TITLE
TDI-38325:Delete return value of Account Name ,Account Key

### PR DESCRIPTION
**Pull request by pyzhou-talend**
**Please check if the PR fulfills these requirements**
https://jira.talendforge.org/browse/TDI-38325
- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/140/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/140/)

**Comment by pyzhou-talend** [comment]
I think the build failed is not related to my commits.

**Comment by gonchar-ivan** [comment]
I found 
"Connection to http://newbuild.talend.com:8081 refused"
line in build log. 
newbuild repository doesn't exist anymore. So, you created branch from old commits in master.
Rebase on latest master should fix build problem.

**Comment by pyzhou-talend** [comment]
Thanks~ Ivan. I will try~

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/247/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/247/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/289/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/289/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/292/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/292/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/293/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/293/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/294/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/294/)

**Pull request merged**
