### PR TITLE
TDI-36822: NPE in tDatasetOutput when performing a full run on a live

### PR DESCRIPTION
**Pull request by wwang-talend**
datase
https://jira.talendforge.org/browse/TDI-36822

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/454/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/454/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/471/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/471/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/484/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/484/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/489/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/489/)

**Comment by gonchar-ivan** [comment]
@wwang-talend 
Is it still needed?

**Comment by wwang-talend** [comment]
no need, so i close it, i will create a new pr for https://jira.talendforge.org/browse/TDI-36822 and https://jira.talendforge.org/browse/TDI-36824

**Pull request closed without merging**
