### PR TITLE
Use beam 0 6 0 tlnd

### PR DESCRIPTION
**Pull request by jbonofre**
**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @RyanSkraba

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/128/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/128/)

**Comment by jbonofre** [comment]
retest this please

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/129/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/129/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/133/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/133/)

**Comment by sgandon** [comment]
@RyanSkraba , could you fix those conflicts please ?

**Pull request closed without merging**
