### PR TITLE
fix(TFD-1176): FilterRow component's REJECT output use the input schema

### PR DESCRIPTION
**Pull request by bchen-talend**
**What is the current behavior?** (You can also link to an open issue here)
Reject schema in FilterRow include one column for error message and one column for original input data

**What is the new behavior?**
make Reject schema same as Input schema

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/304/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/304/)

**Comment by pbailly** [comment]
The current build is broken due to the JDBC component.

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/314/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/314/)

**Comment by bchen-talend** [comment]
I have test it on my local, merge the master into this branch, and run `maven clean install` without all other components, successful

**Pull request merged**
