### PR TITLE
fix(TDI-41943): Integrate new version of Daikon in TCOMPv0 to support Java 11

### PR DESCRIPTION
**Pull request by wwang-talend**
**What is the current behavior?** (You can also link to an open issue here)
Integrate new version of Daikon in TCOMPv0 to support Java 11

**What is the new behavior?**
Integrate new version of Daikon in TCOMPv0 to support Java 11

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/20/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/20/)

**Comment by wwang-talend** [comment]
https://ci-common.datapwn.com/job/components_wwang-talend_TDI-41943

**Comment by wwang-talend** [comment]
can't pass the test now after upgrade the daikon, will check it

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/25/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/25/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/26/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/26/)

**Comment by rmannibucau** [comment]
Please note that most of this work had been done in https://github.com/Talend/components/tree/rmannibucau/java11-support - no need to upgrade daikon BTW - and that upgrading daikon is not sufficient to run on java11. Maybe you can take back this branch to make it merged?

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/27/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/27/)

**Comment by gonchar-ivan** [comment]
not valid anymore
feel free to reopen

**Pull request closed without merging**
