### PR TITLE
fix(TCOMP-330): fix jetty version to 9.2.19.v20160908

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Related to https://jira.talendforge.org/browse/TCOMP-330

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/18/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/18/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/19/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/19/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/22/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/22/)

**Comment by gonchar-ivan** [comment]
It fails components-ee
DONT MERGE

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/29/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/29/)

**Pull request merged**
