### PR TITLE
feat(TDI-38344): Added tests for definition

### PR DESCRIPTION
**Pull request by iistomin-gl**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
- Tests for definitions and properties are absent
- Classes generated from WSDL are included into coverage report and this decreases coverage percentage
- After record type was selected it is not possible to add search condition due to an exception (https://jira.talendforge.org/browse/TDI-38452)
- For some SOAP requests timeout exception can be raised because default timeout is not sufficient

**What is the new behavior?**
- Tests for definitions and properties are present and passed
- Classes generated from WSDL are excluded from coverage report and now coverate report reflects adequate coverage percentage
- After record type was selected it is possible to add search condition
- Default timeout (for connecting and receiving) increased and long running SOAP requests do not cause timeout exception

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/19/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/19/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/20/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/20/)

**Comment by sgandon** [comment]
Please could you fill the PR description to explain what you did.

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/11/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/11/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/16/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/16/)

**Comment by gonchar-ivan** [comment]
Also added Dmytro, because he is Ihor's buddy to review

**Comment by iistomin-gl** [comment]
The PR was split into separate PRs for different fixes

**Pull request closed without merging**
