### PR TITLE
fix(TFD-168): Remove usage of Jetty StringUtil.

### PR DESCRIPTION
**Pull request by pbailly**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Using Jetty StringUtil was causing dependencies error at runtime.

**What is the new behavior?**
Use apache lang3 StringUtils

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/784/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/784/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/786/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/786/)

**Comment by pbailly** [comment]
Valid build on: https://ci-common.datapwn.com/job/components_pull-request_master/793/

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/793/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/793/)

**Pull request merged**
