### PR TITLE
feat(TDP-3329) : use "datalist" widget

### PR DESCRIPTION
**Pull request by charlesnguyen**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Salesforce module nales uses "select" widget

**What is the new behavior?**
Salesforce module nales uses "datalist" widget

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Need https://github.com/Talend/daikon/pull/205/

### CODE REVIEW

**Comment by sgandon** [comment]
wait for the daikon branch to be merged first ;)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/18/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/18/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/22/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/22/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/26/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/26/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/30/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/30/)

**Pull request merged**
