### PR TITLE
chore(TDI-38416): split Marketo modules

### PR DESCRIPTION
**Pull request by undx**
**What is the current behavior?** (You can also link to an open issue here)

https://jira.talendforge.org/browse/TDI-38416

**What is the new behavior?**

Splitted into the following modules
- definition
- runtime
- integration

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [X] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [X] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

Check if this doesn't break the build process.

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/799/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/799/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/809/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/809/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/810/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/810/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/811/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/811/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/812/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/812/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/817/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/817/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/832/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/832/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/833/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/833/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/834/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/834/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/835/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/835/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/837/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/837/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/847/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/847/)

**Comment by akhabali** [comment]
@undx the files above was just for examples.
The full config is in the #878 PR. 

i think you need to define the report path like it was done here for your modules
https://github.com/Talend/components/blob/master/components/components-salesforce/components-salesforce-definition/pom.xml#L12

We need to have a documentation for that. it's not obvious.

@iistomin-gl  Can you please provide a wiki page that describe the configuration to be done for the multi modules coverage report ? 
we have more components that need to be split and this may be very helpful and time saving.

**Comment by undx** [comment]
@akhabali, sorry I didn't catch it completly...

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/849/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/849/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/865/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/865/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/883/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/883/)

**Pull request merged**
