### PR TITLE
feat(TCOMP-332) : Add SSL/TLS common properties

### PR DESCRIPTION
**Pull request by bchen-talend**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
SslProeprties is a copy from tSetKeystore component, which used for DI and Spark component.
https://jira.talendforge.org/browse/TCOMP-332

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/420/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/420/)

**Comment by bchen-talend** [comment]
Hello, I just found I'd better to rename all the https to ssl, I will push one commit soon.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/433/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/433/)

**Comment by sgandon** [comment]
LGTM but there is a build failure to be fixed.

**Comment by bchen-talend** [comment]
thx @sgandon, but I don't know how to fix the error for snowflake unit test, not sure it's relate to this PR

**Comment by sgandon** [comment]
indeed the snowflakes errors are not related to this issue, please merge it.

**Pull request merged**
