### PR TITLE
fix(TDI-40008): tJDBCOutput should hide 'Use batch' when 'Data on action' is 'Update or insert' or 'Insert or update'

### PR DESCRIPTION
**Pull request by wwang-talend**
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-40008

**What is the new behavior?**
https://jira.talendforge.org/browse/TDI-40008

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1669/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1669/)

**Comment by wwang-talend** [comment]
the failed test is not caused by the current fix, will research the bug for the pull request test, maybe a bug for the pr test process.

**Comment by wwang-talend** [comment]
the pr test failed as it use a workspace whose name is like "workspace@2", will fix it

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1672/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1672/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Awwang-talend%2FTDI-40008)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/1673/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/1673/) 
[Sonar results](https://sonar.datapwn.com/overview?id=org.talend.components%3Acomponents%3Awwang-talend%2FTDI-40008)

**Pull request merged**
