### PR TITLE
Bugfix/tdi 37709 date time issues

### PR DESCRIPTION
**Pull request by francisu**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

https://jira.talendforge.org/browse/TDI-37709

**What is the new behavior?**

Dates/times are properly mapped to avro

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/954/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/954/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/956/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/956/)

**Comment by francisu** [comment]
I will add a test case for this on Friday.

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/958/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/958/)

**Comment by francisu** [comment]
I'm just going to go ahead and merge this one, since it's isolated to the Snowflake component and it's small and tested.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/985/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/985/)

**Comment by gonchar-ivan** [comment]
I have checked this PR. It's ok

**Pull request merged**
