### PR TITLE
fix(TDI-38356): keep the order of the dynamic schema as is in azure

### PR DESCRIPTION
**Pull request by akhabali**
table

**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-38356

**What is the new behavior?**
we keep the order as is in the azure table

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/8/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/8/)

**Comment by gonchar-ivan** [comment]
agree with Seb

**Comment by akhabali** [comment]
i added integration test to cover the case of keeping the order of the schema as is in azure

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/39/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/39/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/41/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/41/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/57/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/57/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/8/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/8/)

**Pull request merged**
