### PR TITLE
Bugfix/6.3/tcomp 333 enforcer improvement

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows Talend standard
- [x] Tests for the changes have been added (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

Components tests use di classes

**What is the new behavior?**

Components tests don't use di classes

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Related to https://jira.talendforge.org/browse/TCOMP-333

### CODE REVIEW

**Comment by RyanSkraba** [comment]
Looks good -- I'm not sure why we were using the DI enforcer in these tests, so this is a good idea in every way!

**Comment by gonchar-ivan** [comment]
Thanks for review

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/590/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/590/)

**Comment by sgandon** [comment]
please merge it.

**Pull request merged**
