### PR TITLE
fix(TFD-2023): Require columnName in filter row criteria.

### PR DESCRIPTION
**Pull request by RyanSkraba**
**What is the current behavior?** (You can also link to an open issue here)

You can submit a FilterRow form when there is no columnName specified in one of the subcriteria.

**What is the new behavior?**

The columnName is a required propertie.

**Please check if the PR fulfills these requirements**

- [X] The commit message follows Talend standard
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

**Other information**:

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1052/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1052/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1053/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1053/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1054/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1054/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1055/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1055/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1056/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1056/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1057/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1057/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1058/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1058/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1060/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1060/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1062/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1062/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1064/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1064/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1063/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1063/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1067/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1067/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1070/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1070/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/1079/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/1079/)

**Comment by RyanSkraba** [comment]
I merged this without a successful build. The CI failures on this branch seem to be unrelated to the changes here.

Normally, I would have waited anyway, but a merged PR on daikon (https://github.com/Talend/daikon/pull/274) is causing master to fail unit tests now for other PRs now.

**Pull request merged**
